APT::FTPArchive::Release::Origin "DenncoLABS";
APT::FTPArchive::Release::Label "Dennco Olympus Command";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Dennco Olympus Command apt repository";
